### ISSUE TITLE
Handle Failed Plugin Loading

### ISSUE THREAD

**Issue by TomRichter** [PULSAR-Modders/pulsar-plugin-loader#15]
Plugins that fail to load currently soft crash the game.  This isn't too graceful, although it's been necessary to leave it this way since we haven't had a way to display broken plugins in game.

When a plugin fails to load, it should be handled such that other plugins and the game can still continue.  The exception should still be displayed in the log.  Additionally, an in game message should appear that states which plugins have failed in total.

**Comment by DragonFire47** [comment]
This issue was resolved a while ago
