### ISSUE TITLE
Add Discord link to Main Menu

### ISSUE THREAD

**Issue by TomRichter** [PULSAR-Modders/pulsar-plugin-loader#9]
To make it easier to find us, a Discord link should be added to the main menu.  A simple Discord icon styled to look like a button should suffice.

More generally, this should be implemented as a collection of icons/buttons that we can add to in the future.  Have it appear in the bottom left corner since that space is dark/contrasting and unused.

**Comment by Galaxy-Creator** [comment]
Well actually, what's the discord ?

**Comment by TomRichter** [comment]
https://discord.gg/j3Pydn6

**Comment by DragonFire47** [comment]
Added link to Mod management GUI
